namespace owobot_csharp.Subreddits;

public enum Explicit
{
    manga,
    AnimeART,
    awwnime,
    wholesomeyuri,
    Joshi_Kosei,
    AnimeBlush,
    tsunderes,
    Usagimimi,
    kitsunemimi,
    animeponytails,
    tyingherhairup,
    OfficialSenpaiHeat,
    ChurchofBelly,
    Moescape,
    MoeStash,
    TwoDeeArt,
    headpats,
    cutelittlefangs,
    kemonomimi,
    twintails,
    pouts,
    gao,
    animelegs,
    ZettaiRyouiki,
    thighdeology,
    Animewallpaper,
    pantsu,
    Patchuu,
    animehotbeverages,
    AnimeLounging,
    silverhair,
    shorthairedwaifus,
}