//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace owobot_csharp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Handlers_ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Handlers_ru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("owobot_csharp.Resources.Handlers.ru-RU", typeof(Handlers_ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приветик! Я owobot {0} - бот, который прислылает милых девочек!
        ///
        ///Я написана на C# с использованием .NET 6, беру картинки с reddit, мультипоточна и полностью совместима с групповыми чатами. Не бойтесь отправлять мне по 25-50 запросов за раз, я справлюсь с этим!
        ///
        ///Если надоело читать и хочется уже видеть аниме девочек, то вам сюда: /get По умолчанию я не буду присылать вам NSFW контент, однако Вы можете настроить это тут: /nsfw Также вы можете поменять язык здесь: /language
        ///
        ///Пару слов по поводу приватнос [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oa! Вы решили сменить язык?
        ///
        ///На данный момент установлен русский язык. Вот что Вы можете сделать:
        ////language_en to switch to english
        ////language_ru чтобы переключится на русский.
        /// </summary>
        internal static string LanguageInfo {
            get {
                return ResourceManager.GetString("LanguageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пам! Вот вам картинка с {0}
        ///Название поста: {1}
        ///NSFW: {2}
        ///Ссылка на оригинал: {3}
        ///Ссылка на пост: {4}.
        /// </summary>
        internal static string ReturnPic {
            get {
                return ResourceManager.GetString("ReturnPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поняла вас! Теперь я буду отвечать вам на русском языке!.
        /// </summary>
        internal static string SetLanguage {
            get {
                return ResourceManager.GetString("SetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать, {0}!
        ///
        ///Чтобы получить больше информации напишите /info
        ///Для быстрого начала, просто напишите /get
        ///
        ///Также нажмите на иконочку со слешем у клавиатуры чтобы узнать о командах..
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я жива!
        ///
        ///Uptime: {0} дней {1} . Всего запросов: {2}
        ///NSFW для этого чата: {3}
        ///Версия бота: {4}.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
    }
}
