//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace owobot_csharp.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Handlers_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Handlers_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("owobot_csharp.Resources.Handlers_en_US", typeof(Handlers_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        internal static string SetLanguage {
            get {
                return ResourceManager.GetString("SetLanguage", resourceCulture);
            }
        }
        
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        internal static string LanguageInfo {
            get {
                return ResourceManager.GetString("LanguageInfo", resourceCulture);
            }
        }
        
        internal static string ReturnPic {
            get {
                return ResourceManager.GetString("ReturnPic", resourceCulture);
            }
        }
        
        internal static string GetStatus {
            get {
                return ResourceManager.GetString("GetStatus", resourceCulture);
            }
        }
        
        internal static string NsfwStatus {
            get {
                return ResourceManager.GetString("NsfwStatus", resourceCulture);
            }
        }
        
        internal static string SetNsfwOn {
            get {
                return ResourceManager.GetString("SetNsfwOn", resourceCulture);
            }
        }
        
        internal static string SetNsfwOff {
            get {
                return ResourceManager.GetString("SetNsfwOff", resourceCulture);
            }
        }
        
        internal static string NsfwSettingException {
            get {
                return ResourceManager.GetString("NsfwSettingException", resourceCulture);
            }
        }
        
        internal static string LewdDetected {
            get {
                return ResourceManager.GetString("LewdDetected", resourceCulture);
            }
        }
        
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        internal static string Info_Chat {
            get {
                return ResourceManager.GetString("Info_Chat", resourceCulture);
            }
        }
        
        internal static string GetStatus_Chat {
            get {
                return ResourceManager.GetString("GetStatus_Chat", resourceCulture);
            }
        }
        
        internal static string LanguageInfo_Chat {
            get {
                return ResourceManager.GetString("LanguageInfo_Chat", resourceCulture);
            }
        }
        
        internal static string LewdDetected_Chat {
            get {
                return ResourceManager.GetString("LewdDetected_Chat", resourceCulture);
            }
        }
        
        internal static string NsfwSettingException_Chat {
            get {
                return ResourceManager.GetString("NsfwSettingException_Chat", resourceCulture);
            }
        }
        
        internal static string ReturnPic_Chat {
            get {
                return ResourceManager.GetString("ReturnPic_Chat", resourceCulture);
            }
        }
        
        internal static string SetLanguage_Chat {
            get {
                return ResourceManager.GetString("SetLanguage_Chat", resourceCulture);
            }
        }
        
        internal static string SetNsfwOff_Chat {
            get {
                return ResourceManager.GetString("SetNsfwOff_Chat", resourceCulture);
            }
        }
        
        internal static string SetNsfwOn_Chat {
            get {
                return ResourceManager.GetString("SetNsfwOn_Chat", resourceCulture);
            }
        }
        
        internal static string UnknowsCommand_Chat {
            get {
                return ResourceManager.GetString("UnknowsCommand_Chat", resourceCulture);
            }
        }
        
        internal static string NsfwStatus_Chat {
            get {
                return ResourceManager.GetString("NsfwStatus_Chat", resourceCulture);
            }
        }
        
        internal static string NsfwSettingException_NotEnoughRights_Chat {
            get {
                return ResourceManager.GetString("NsfwSettingException_NotEnoughRights_Chat", resourceCulture);
            }
        }
    }
}
